<a href="https://colab.research.google.com/github/mohammadakhoundi1/recommender-system/blob/master/Twitter-Sentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 55.9 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import gensim

In [ ]:
!gensim.__version__

/bin/bash: line 1: gensim.__version__: command not found

In [44]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import random
from tqdm import tqdm
from gensim.models import Word2Vec
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.model_selection import train_test_split

In [20]:
!mkdir -p ~/.kaggle && echo KGAT_e5d58ff9f1c532bff994bc15674969c5 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

In [23]:
!kaggle datasets download -d mohammadakhoundi/Retail --unzip

Dataset URL: https://www.kaggle.com/datasets/mohammadakhoundi/Retail
License(s): MIT
Downloading Retail.zip to /content
100% 21.8M/21.8M [00:01<00:00, 16.0MB/s]

In [24]:
df = pd.read_excel('OnlineRetail.xlsx')

In [39]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [26]:
df.shape

(541909, 8)

In [27]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [29]:
df.dropna(inplace=True)

In [30]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [31]:
df.shape

(406829, 8)

In [32]:
df['StockCode'] = df['StockCode'].astype(str)

In [33]:
customers = df['CustomerID'].unique().tolist()
len(customers)

4372

In [34]:
df['Quantity'].unique()

array([     6,      8,      2,     32,      3,      4,     24,     12,
           48,     18,     20,     36,     80,     64,     10,    120,
           96,     23,      5,      1,     -1,     50,     40,    100,
          192,    432,    144,    288,    -12,    -24,     16,      9,
          128,     25,     30,     28,      7,     72,    200,    600,
          480,     -6,     14,     -2,     -4,     -5,     -7,     -3,
           11,     70,    252,     60,    216,    384,     27,    108,
           52,  -9360,     75,    270,     42,    240,     90,    320,
           17,   1824,    204,     69,    -36,   -192,   -144,    160,
         2880,   1400,     19,     39,    -48,    -50,     56,     13,
         1440,     -8,     15,    720,    -20,    156,    324,     41,
          -10,    -72,    -11,    402,    378,    150,    300,     22,
           34,    408,    972,    208,   1008,     26,   1000,    -25,
         1488,    250,   1394,    400,    110,    -14,     37,    -33,
           78,     -9,     21,    272,     84,    -47,    -18,    -96,
           47,    -15,    -30,   1728,     38,    -60,    -16,     53,
         -240,     76,    576,    -32,     29,   2400,    500,    -80,
          180,   -300,   -500,    -23,    -13,    960,    -21,   1296,
         -150,    -17,    147,    168,    256,    -40,   -100,     54,
           31,    860,   1010,   1356,   1284,    186,    114,    360,
         1930,   2000,   3114,   1300,    670,    176,    648,     62,
        74215, -74215,     89,     33,     46,   -120,    112,    456,
          900,   -600,    -42,    -94,     45,    130,   2592,    420,
          800,     35,   1200,    864,    504,    -76,   -200,   1056,
         1500,    280,    407,    141,   3906,   1152,    198,    117,
         -720,    125,    -86,     81,    -35,    768,     88,     43,
          700,   -102,   2160,     55,    -49,    342,    304,    640,
          220,    350,    -46,    -64,    312,    392,   -624,    -27,
          330,    151,   -432,    -58,     44,   -670,  -1300,  -1930,
        -2000,  -3114,    462,     66,    492,    273,     65,     85,
          -51,   -960,   1350,    428,  -1350,    336,    101,    132,
          227,   2700,    222,    228,    246,    906,    756,    888,
          552,    224,    738,    608,   4300,    276,    -52,     58,
           98,     51,     74,   1600,    323,    -22,   1515,  -1515,
          660,    104,   -420,    264,    188,    588,    612,    152,
          -19,   -480,     49,   -164,   -160,    430,    701,    828,
          540,    696,    560,   -576,   -108,   -250,   -408,    121,
          512,    -37,    291,   3186,     83,     87,     79,   -360,
          -28,    -75,    109,   -121,    129,    261,    352,    102,
         -288,    348,   1900,    157,    -39,    116,    968,    684,
          824,   -828,   -701,    196,    124,    248,    410,    236,
          230,    210,    448,   -140,   -400,   -252,   -110,   -334,
         -318,   -126,   -113,   -180,    140,     86,    840,    -38,
          450,     93,    494,     92,   1788,    624,    744,    416,
          496,    396,    306,   1878,   1944,    666,    708,   1428,
          852,   1412,    528,   -756,   -152,    -85,    -34,   -312,
          -79,    -43,    -31,    183,   -186,    -53,    -82,    -70,
          -68,   1540,  -1200,   -130,   -220,    672,    -26,    -29,
           67,   -840,  -1296,     63,     94,    255,     57,    126,
          468,   -468,   -324,   -168,   4800,    -66,   -112,    912,
         1992,    136,   3000,    -45,    232,    832,    992,    630,
         1020,   2100,    162,   -162,    -67,   -276,   -184,    234,
          244,   -244,   -234,   -132,  12540,     95,    760,    139,
          115,    774,   2040,   1120,     59,    490,    388,    620,
         1404,    698,  80995, -80995])

In [35]:
len(df['Quantity'].unique())

436

In [36]:
df = df[df['Quantity']>0]

In [37]:
df.shape

(397924, 8)

In [38]:
df['Quantity'].unique()

array([    6,     8,     2,    32,     3,     4,    24,    12,    48,
          18,    20,    36,    80,    64,    10,   120,    96,    23,
           5,     1,    50,    40,   100,   192,   432,   144,   288,
          16,     9,   128,    25,    30,    28,     7,    72,   200,
         600,   480,    14,    11,    70,   252,    60,   216,   384,
          27,   108,    52,    75,   270,    42,   240,    90,   320,
          17,  1824,   204,    69,   160,  2880,  1400,    19,    39,
          56,    13,  1440,    15,   720,   156,   324,    41,   402,
         378,   150,   300,    22,    34,   408,   972,   208,  1008,
          26,  1000,  1488,   250,  1394,   400,   110,    37,    78,
          21,   272,    84,    47,  1728,    38,    53,    76,   576,
          29,  2400,   500,   180,   960,  1296,   147,   168,   256,
          54,    31,   860,  1010,  1356,  1284,   186,   114,   360,
        1930,  2000,  3114,  1300,   670,   176,   648,    62, 74215,
          89,    33,    46,   112,   456,   900,    45,   130,  2592,
         420,   800,    35,  1200,   864,   504,  1056,  1500,   280,
         407,   141,  3906,  1152,   198,   117,   125,    81,   768,
          88,    43,   700,  2160,    55,   342,   304,   640,   220,
         350,   312,   392,   330,   151,    44,   462,    66,   492,
         273,    65,    85,  1350,   428,   336,   101,   132,   227,
        2700,   222,   228,   246,   906,   756,   888,   552,   224,
         738,   608,  4300,   276,    58,    98,    51,    74,  1600,
         323,  1515,   660,   104,   264,   188,   588,   612,   152,
          49,   430,   701,   828,   540,   696,   560,   121,   512,
         291,  3186,    83,    87,    79,   109,   129,   261,   352,
         102,   348,  1900,   157,   116,   968,   684,   824,   196,
         124,   248,   410,   236,   230,   210,   448,   140,    86,
         840,   450,    93,   494,    92,  1788,   624,   744,   416,
         496,   396,   306,  1878,  1944,   666,   708,  1428,   852,
        1412,   528,   183,  1540,   672,    67,    63,    94,   255,
          57,   126,   468,  4800,   912,  1992,   136,  3000,   232,
         832,   992,   630,  1020,  2100,   162,   234,   244, 12540,
          95,   760,   139,   115,   774,  2040,  1120,    59,   490,
         388,   620,  1404,   698, 80995])

In [42]:
x = df.drop('StockCode',axis=1)
y = df.StockCode

In [45]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)